#!/usr/bin/env bash
# generators/go.sh — Go 代码骨架生成器（纯 bash + jq）
# 约定: PascalCase -> snake_case 文件，类型 + 方法
# 模板: 若 templates/go/<name>.tpl 存在, 用 render_template 渲染;
#       否则回退到内联 heredoc (向后兼容)。
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
source "$(dirname "${BASH_SOURCE[0]}")/_templates.sh"

LANG="go"
LANG_DIR="${OUTPUT_DIR}/${LANG}"
mkdir -p "$LANG_DIR"

# 每个 module -> 包目录
PACKAGE_NAME=$(basename "$LANG_DIR" | tr '[:upper:]' '[:lower:]')

for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
    m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
    m_desc=$(jq -r ".modules[$mi].description" "$STRUCT_FILE")
    m_dir="${LANG_DIR}/${m_name}"
    mkdir -p "$m_dir"

    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_desc=$(jq -r ".modules[$mi].components[$ci].description" "$STRUCT_FILE")
        c_exports=$(jq -c ".modules[$mi].components[$ci].exports // []" "$STRUCT_FILE")
        c_imports=$(jq -c ".modules[$mi].components[$ci].imports // .modules[$mi].components[$ci].depends_on // []" "$STRUCT_FILE")
        c_optional=$(jq -r ".modules[$mi].components[$ci].optional // false" "$STRUCT_FILE")
        c_todos=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")
        c_files=$(jq -c ".modules[$mi].components[$ci].files // []" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")

        # 多文件支持
        if [[ "$(echo "$c_files" | jq 'length')" -gt 0 ]]; then
            file_0=$(echo "$c_files" | jq -r '.[0]')
            file="${m_dir}/${file_0}"
        else
            file="${m_dir}/${snake}.go"
        fi

        if should_regenerate "$file" "$STRUCT_FILE"; then
            struct_fields=""
            while IFS= read -r e; do
                [[ -z "$e" ]] && continue
                struct_fields+=$'\t'"${e} interface{} // ${e}"$'\n'
            done < <(echo "$c_exports" | jq -r '.[]')

            imports_block=""
            seen_pkgs=""
            while IFS= read -r dep; do
                [[ -z "$dep" ]] && continue
                dep_module=$(module_of "$dep")
                [[ -z "$dep_module" ]] && continue
                if [[ "$dep_module" != "$m_name" && "$seen_pkgs" != *"|$dep_module|"* ]]; then
                    imports_block+=$'\t'"\"${PROJECT_NAME:-app}/${dep_module}\""$'\n'
                    seen_pkgs+="|${dep_module}|"
                fi
            done < <(echo "$c_imports" | jq -r '.[]')

            todo_block=""
            if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                todo_block="// TODO:"$'\n'
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    todo_block+="//   - ${line}"$'\n'
                done < <(echo "$c_todos" | jq -r '.[] | "\(.id): \(.task) [priority=\(.priority // "medium")] blocks=\(.blocks // [])"')
            fi

            vars_file=$(mktemp)
            {
                printf 'component_name=%s\n' "$(encode_value "${c_name}")"
                printf 'module_name=%s\n' "$(encode_value "${m_name}")"
                printf 'module_description=%s\n' "$(encode_value "${m_desc}")"
                printf 'snake_name=%s\n' "$(encode_value "${snake}")"
                printf 'description=%s\n' "$(encode_value "${c_desc}")"
                printf 'imports_block=%s\n' "$(encode_value "${imports_block}")"
                printf 'struct_fields=%s\n' "$(encode_value "${struct_fields}")"
                printf 'todos_block=%s\n' "$(encode_value "${todo_block}")"
                printf 'optional_go=%s\n' "$(encode_value "${c_optional}")"
                printf 'acceptance_criteria=\n'
            } > "$vars_file"

            if ! render_to_file "$file" "go" "component" "$vars_file"; then
                # 回退
                cat > "$file" <<EOF
// Package ${m_name} — ${m_desc}
// Auto-generated by bootstrap.sh
package ${m_name}

import (
	"errors"
${imports_block})
// ${c_desc}
type ${c_name} struct {
${struct_fields}	Optional bool
}

// Name 用于注册中心识别
const Name${c_name} = "${c_name}"

// New 构造一个 ${c_name} 实例
func New${c_name}() *${c_name} {
	return &${c_name}{Optional: ${c_optional}}
}
${todo_block}
// Call 执行 ${c_name} 的核心逻辑
func (c *${c_name}) Call() (interface{}, error) {
	return nil, errors.New("${c_name}.Call() 待实现")
}
EOF
            fi
            rm -f "$vars_file"
            mark_generated "$file" "$STRUCT_FILE"
            say "  [OK] go: ${m_name}/$(basename "$file")"
        else
            say "  [SKIP] go: ${m_name}/$(basename "$file") (unchanged)"
        fi

        # 多文件模式下的 test stub
        if [[ "$(echo "$c_files" | jq 'length')" -gt 1 ]]; then
            test_filename=$(echo "$c_files" | jq -r '.[1] // "test_'${snake}'.go"')
            tests_dir="${m_dir}/tests"
            mkdir -p "$tests_dir"
            test_path="${tests_dir}/${test_filename}"
            if should_regenerate "$test_path" "$STRUCT_FILE"; then
                test_functions=""
                todos_block_go=""
                if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                    while IFS= read -r todo; do
                        [[ -z "$todo" ]] && continue
                        todo_id=$(echo "$todo" | jq -r '.id')
                        todo_task=$(echo "$todo" | jq -r '.task')
                        todo_ac=$(echo "$todo" | jq -r '.acceptance_criteria // ""')
                        func_suffix=$(to_pascal "$todo_id")
                        todos_block_go+="// TODO ${todo_id}: ${todo_task}"$'\n'
                        if [[ -n "${todo_ac}" && "${todo_ac}" != "null" && "${todo_ac}" != "" ]]; then
                            todos_block_go+="//   acceptance: ${todo_ac}"$'\n'
                        fi
                        test_functions+="func Test${func_suffix}(t *testing.T) {"$'\n'
                        test_functions+="	// TODO: replace with real assertion for: ${todo_task}"$'\n'
                        test_functions+="	t.Fatal(\"stub for ${todo_id}\")"$'\n'
                        test_functions+="}"$'\n'$'\n'
                    done < <(echo "$c_todos" | jq -c '.[]')
                fi

                vars_file2=$(mktemp)
                {
                    printf 'component_name=%s\n' "$(encode_value "${c_name}")"
                    printf 'module_name=%s\n' "$(encode_value "${m_name}")"
                    printf 'snake_name=%s\n' "$(encode_value "${snake}")"
                    printf 'todos_block=%s\n' "$(encode_value "${todos_block_go}")"
                    printf 'test_functions=%s\n' "$(encode_value "${test_functions}")"
                } > "$vars_file2"

                if ! render_to_file "$test_path" "go" "test_stub" "$vars_file2"; then
                    cat > "$test_path" <<EOF
// Auto-generated test stubs for ${c_name} (module: ${m_name})
package ${m_name}

import "testing"
${test_functions}
EOF
                fi
                rm -f "$vars_file2"
                mark_generated "$test_path" "$STRUCT_FILE"
                say "  [OK] go: ${m_name}/tests/${test_filename}"
            else
                say "  [SKIP] go: ${m_name}/tests/${test_filename} (unchanged)"
            fi
        fi
    done

    # per-module todo.json
    if [[ "$(jq "[.modules[$mi].components[].todos // [] | length] | add // 0" "$STRUCT_FILE")" -gt 0 ]]; then
        todo_file="${m_dir}/todo.json"
        if should_regenerate "$todo_file" "$STRUCT_FILE"; then
            m_name_jq=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
            jq --arg mod "${m_name_jq}" "{module: .modules[$mi].name, description: .modules[$mi].description, todos: [.modules[$mi].components[] | . as \$c | .todos[]? | . + {module: \$mod, component: \$c.name}]}" "${STRUCT_FILE}" \
                > "$todo_file"
            mark_generated "$todo_file" "$STRUCT_FILE"
            say "  [OK] go: ${m_name}/todo.json"
        else
            say "  [SKIP] go: ${m_name}/todo.json (unchanged)"
        fi
    fi
done

# go.mod
GO_MOD="${LANG_DIR}/go.mod"
if should_regenerate "$GO_MOD" "$STRUCT_FILE"; then
    vars_file=$(mktemp)
    {
        printf 'module_path=%s\n' "${PROJECT_NAME:-app}"
    } > "$vars_file"
    if ! render_to_file "$GO_MOD" "go" "go_mod" "$vars_file"; then
        cat > "$GO_MOD" <<MOD
module ${PROJECT_NAME:-app}

go 1.22
MOD
    fi
    rm -f "$vars_file"
    mark_generated "$GO_MOD" "$STRUCT_FILE"
    say "  [OK] go: go.mod"
else
    say "  [SKIP] go: go.mod (unchanged)"
fi

echo "  [OK] go 生成完成: $LANG_DIR/"
