#!/usr/bin/env bash
# generators/rust.sh — Rust 代码骨架生成器（纯 bash + jq）
# 约定: 每个 module -> 子模块 (mod.rs), 每个 component -> pub struct + impl
# 模板: 若 templates/rust/<name>.tpl 存在, 用 render_template 渲染;
#       否则回退到内联 heredoc (向后兼容)。
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
source "$(dirname "${BASH_SOURCE[0]}")/_templates.sh"

LANG="rust"
LANG_DIR="${OUTPUT_DIR}/${LANG}"
mkdir -p "$LANG_DIR/src"

# JSON 字符串数组 -> Rust Vec<String> 字面量
to_rust_str_vec() {
    local arr="$1"
    if [[ "$arr" == "[]" ]]; then echo "Vec::new()"; return; fi
    local items=""
    while IFS= read -r s; do
        [[ -z "$s" ]] && continue
        items+="        String::from(\"$s\"),"$'\n'
    done < <(echo "$arr" | jq -r '.[]')
    echo "vec!["$'\n'"${items}    ]"
}

# 每个 module -> src/<module>/mod.rs
for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
    m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
    m_desc=$(jq -r ".modules[$mi].description" "$STRUCT_FILE")
    m_dir="${LANG_DIR}/src/${m_name}"
    mkdir -p "$m_dir"

    # 收集所有 component 的 pub mod / pub use 行
    mod_lines=""
    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")
        mod_lines+="pub mod ${snake};"$'\n'
        mod_lines+="pub use ${snake}::${c_name};"$'\n'
    done

    # per-component #[test] 块
    tests_block=""
    tests_block+=$'\n'"#[cfg(test)]"$'\n'
    tests_block+="mod tests {"$'\n'
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_todos=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")
        tests_block+="    use super::${snake}::${c_name};"$'\n'
        tests_block+="    #[test]"$'\n'
        tests_block+="    fn ${snake}_can_construct() {"$'\n'
        tests_block+="        let _ = ${c_name}::new();"$'\n'
        tests_block+="    }"$'\n'

        # per-todo test stub
        if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
            while IFS= read -r todo; do
                [[ -z "$todo" ]] && continue
                todo_id=$(echo "$todo" | jq -r '.id')
                todo_task=$(echo "$todo" | jq -r '.task')
                todo_ac=$(echo "$todo" | jq -r '.acceptance_criteria // ""')
                tests_block+="    // TODO ${todo_id}: ${todo_task}"$'\n'
                if [[ -n "${todo_ac}" && "${todo_ac}" != "null" && "${todo_ac}" != "" ]]; then
                    tests_block+="    //   acceptance: ${todo_ac}"$'\n'
                fi
                tests_block+="    #[test]"$'\n'
                tests_block+="    fn ${todo_id}() {"$'\n'
                tests_block+="        // TODO: replace with real assertion for: ${todo_task}"$'\n'
                tests_block+="        unimplemented!(\"stub for ${todo_id}\")"$'\n'
                tests_block+="    }"$'\n'
            done < <(echo "$c_todos" | jq -c '.[]')
        fi
    done
    tests_block+="}"$'\n'

    # mod.rs 始终重新生成
    vars_file=$(mktemp)
    {
        printf 'module_name=%s\n' "$(encode_value "${m_name}")"
        printf 'module_description=%s\n' "$(encode_value "${m_desc}")"
        printf 'mod_lines=%s\n' "$(encode_value "${mod_lines}")"
        printf 'tests_block=%s\n' "$(encode_value "${tests_block}")"
    } > "$vars_file"

    if ! render_to_file "${m_dir}/mod.rs" "rust" "module_mod" "$vars_file"; then
        # 回退
        cat > "${m_dir}/mod.rs" <<EOF
//! Module: ${m_name}
//!
//! ${m_desc}

// Auto-generated by bootstrap.sh
${mod_lines}
${tests_block}
EOF
    fi
    rm -f "$vars_file"
    say "  [OK] rust: ${m_name}/mod.rs"

    # 每个 component -> pub struct + impl block
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_desc=$(jq -r ".modules[$mi].components[$ci].description" "$STRUCT_FILE")
        c_exports=$(jq -c ".modules[$mi].components[$ci].exports // []" "$STRUCT_FILE")
        c_imports=$(jq -c ".modules[$mi].components[$ci].imports // .modules[$mi].components[$ci].depends_on // []" "$STRUCT_FILE")
        c_optional=$(jq -r ".modules[$mi].components[$ci].optional // false" "$STRUCT_FILE")
        c_todos=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")
        c_files=$(jq -c ".modules[$mi].components[$ci].files // []" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")

        # 多文件支持
        if [[ "$(echo "$c_files" | jq 'length')" -gt 0 ]]; then
            file_0=$(echo "$c_files" | jq -r '.[0]')
            file="${m_dir}/${file_0}"
        else
            file="${m_dir}/${snake}.rs"
        fi

        if should_regenerate "$file" "$STRUCT_FILE"; then
            exports_rust=$(to_rust_str_vec "$c_exports")
            imports_rust=$(to_rust_str_vec "$c_imports")

            use_block=""
            while IFS= read -r dep; do
                [[ -z "$dep" ]] && continue
                dep_module=$(module_of "$dep")
                [[ -z "$dep_module" ]] && continue
                dep_snake=$(to_snake "$dep")
                if [[ "$dep_module" == "$m_name" ]]; then
                    use_block+="use super::${dep_snake}::${dep};"$'\n'
                else
                    use_block+="use crate::${dep_module}::${dep_snake}::${dep};"$'\n'
                fi
            done < <(echo "$c_imports" | jq -r '.[]')

            struct_fields=""
            while IFS= read -r e; do
                [[ -z "$e" ]] && continue
                struct_fields+="    pub ${e}: Option<String>,  // ${e}"$'\n'
            done < <(echo "$c_exports" | jq -r '.[]')

            struct_field_inits=""
            while IFS= read -r e; do
                [[ -z "$e" ]] && continue
                struct_field_inits+="            ${e}: None,"$'\n'
            done < <(echo "$c_exports" | jq -r '.[]')

            if [[ "$(echo "$c_exports" | jq 'length')" -eq 0 ]]; then
                exports_const_line="pub const EXPORTS: &[&str] = &[];"
            else
                _items=$(echo "$c_exports" | jq -r 'map("\"" + . + "\"") | join(", ")')
                exports_const_line="pub const EXPORTS: &[&str] = &[${_items}];"
            fi

            todo_lines=""
            if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                todo_lines="    // TODO:"$'\n'
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    todo_lines+="    //   - ${line}"$'\n'
                done < <(echo "$c_todos" | jq -r '.[] | "\(.id): \(.task) [priority=\(.priority // "medium")] blocks=\(.blocks // [])"')
            fi

            ac_block=""
            if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                ac_raw=$(echo "$c_todos" | jq -r '.[] | select(.acceptance_criteria) | "Acceptance: \(.acceptance_criteria)"')
                if [[ -n "$ac_raw" ]]; then
                    while IFS= read -r ac_line; do
                        [[ -z "$ac_line" ]] && continue
                        ac_block+="// ${ac_line}"$'\n'
                    done <<< "$ac_raw"
                fi
            fi

            vars_file2=$(mktemp)
            {
                printf 'component_name=%s\n' "$(encode_value "${c_name}")"
                printf 'module_name=%s\n' "$(encode_value "${m_name}")"
                printf 'snake_name=%s\n' "$(encode_value "${snake}")"
                printf 'description=%s\n' "$(encode_value "${c_desc}")"
                printf 'use_block=%s\n' "$(encode_value "${use_block}")"
                printf 'imports_block=%s\n' "$(encode_value "${use_block}")"
                printf 'struct_fields=%s\n' "$(encode_value "${struct_fields}")"
                printf 'struct_field_inits=%s\n' "$(encode_value "${struct_field_inits}")"
                printf 'exports_const_line=%s\n' "$(encode_value "${exports_const_line}")"
                printf 'exports_rust=%s\n' "$(encode_value "${exports_rust}")"
                printf 'imports_rust=%s\n' "$(encode_value "${imports_rust}")"
                printf 'todos_block=%s\n' "$(encode_value "${todo_lines}")"
                printf 'acceptance_criteria=%s\n' "$(encode_value "${ac_block}")"
                printf 'optional_rust=%s\n' "$(encode_value "${c_optional}")"
            } > "$vars_file2"

            if ! render_to_file "$file" "rust" "component" "$vars_file2"; then
                # 回退
                cat > "$file" <<EOF
//! Component: ${c_name}
//!
//! ${c_desc}

use serde::{Deserialize, Serialize};
use std::any::Any;
${use_block}
/// ${c_desc}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ${c_name} {
${struct_fields}    pub optional: bool,
}

pub const NAME: &str = "${c_name}";
${exports_const_line}
${todo_lines}impl ${c_name} {
    pub fn new() -> Self {
        Self {
${struct_field_inits}            optional: ${c_optional},
        }
    }

    /// 执行 ${c_name} 的核心逻辑
    pub fn call(&self) -> Box<dyn Any> {
        unimplemented!("${c_name}::call() 待实现")
    }
}

impl Default for ${c_name} {
    fn default() -> Self { Self::new() }
}
EOF
            fi
            rm -f "$vars_file2"
            mark_generated "$file" "$STRUCT_FILE"
            say "  [OK] rust: ${m_name}/$(basename "$file")"
        else
            say "  [SKIP] rust: ${m_name}/$(basename "$file") (unchanged)"
        fi

        # 多文件模式下的 test stub
        if [[ "$(echo "$c_files" | jq 'length')" -gt 1 ]]; then
            test_filename=$(echo "$c_files" | jq -r '.[1] // "test_'${snake}'.rs"')
            tests_dir="${m_dir}/tests"
            mkdir -p "$tests_dir"
            test_path="${tests_dir}/${test_filename}"
            if should_regenerate "$test_path" "$STRUCT_FILE"; then
                test_functions=""
                todos_block_rs=""
                if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                    while IFS= read -r todo; do
                        [[ -z "$todo" ]] && continue
                        todo_id=$(echo "$todo" | jq -r '.id')
                        todo_task=$(echo "$todo" | jq -r '.task')
                        todo_ac=$(echo "$todo" | jq -r '.acceptance_criteria // ""')
                        todos_block_rs+="// TODO ${todo_id}: ${todo_task}"$'\n'
                        if [[ -n "${todo_ac}" && "${todo_ac}" != "null" && "${todo_ac}" != "" ]]; then
                            todos_block_rs+="//   acceptance: ${todo_ac}"$'\n'
                        fi
                        test_functions+="    #[test]"$'\n'
                        test_functions+="    fn ${todo_id}() {"$'\n'
                        test_functions+="        // TODO: replace with real assertion for: ${todo_task}"$'\n'
                        test_functions+="        unimplemented!(\"stub for ${todo_id}\")"$'\n'
                        test_functions+="    }"$'\n'$'\n'
                    done < <(echo "$c_todos" | jq -c '.[]')
                fi

                vars_file3=$(mktemp)
                {
                    printf 'component_name=%s\n' "$(encode_value "${c_name}")"
                    printf 'module_name=%s\n' "$(encode_value "${m_name}")"
                    printf 'snake_name=%s\n' "$(encode_value "${snake}")"
                    printf 'todos_block=%s\n' "$(encode_value "${todos_block_rs}")"
                    printf 'test_functions=%s\n' "$(encode_value "${test_functions}")"
                } > "$vars_file3"

                if ! render_to_file "$test_path" "rust" "test_stub" "$vars_file3"; then
                    cat > "$test_path" <<EOF
//! Auto-generated test stubs for ${c_name} (module: ${m_name})

#[cfg(test)]
mod ${snake}_tests {
    use super::${snake}::${c_name};
${test_functions}}
EOF
                fi
                rm -f "$vars_file3"
                mark_generated "$test_path" "$STRUCT_FILE"
                say "  [OK] rust: ${m_name}/tests/${test_filename}"
            else
                say "  [SKIP] rust: ${m_name}/tests/${test_filename} (unchanged)"
            fi
        fi
    done

    # per-module todo.json
    if [[ "$(jq "[.modules[$mi].components[].todos // [] | length] | add // 0" "$STRUCT_FILE")" -gt 0 ]]; then
        todo_file="${m_dir}/todo.json"
        if should_regenerate "$todo_file" "$STRUCT_FILE"; then
            module_name_jq=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
            jq --arg mod "${module_name_jq}" "{module: .modules[$mi].name, description: .modules[$mi].description, todos: [.modules[$mi].components[] | . as \$c | .todos[]? | . + {module: \$mod, component: \$c.name}]}" "${STRUCT_FILE}" \
                > "$todo_file"
            mark_generated "$todo_file" "$STRUCT_FILE"
            say "  [OK] rust: ${m_name}/todo.json"
        else
            say "  [SKIP] rust: ${m_name}/todo.json (unchanged)"
        fi
    fi
done

# Cargo.toml
CRATE_NAME=$(basename "$LANG_DIR" | tr '[:upper:]' '[:lower:]' | tr - _)
CARGO_FILE="${LANG_DIR}/Cargo.toml"
if should_regenerate "$CARGO_FILE" "$STRUCT_FILE"; then
    vars_file=$(mktemp)
    {
        printf 'crate_name=%s\n' "$(encode_value "${CRATE_NAME}")"
    } > "$vars_file"
    if ! render_to_file "$CARGO_FILE" "rust" "cargo" "$vars_file"; then
        cat > "$CARGO_FILE" <<TOML
[package]
name = "${CRATE_NAME}"
version = "0.1.0"
edition = "2021"

[lib]
name = "${CRATE_NAME}"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
TOML
    fi
    rm -f "$vars_file"
    mark_generated "$CARGO_FILE" "$STRUCT_FILE"
    say "  [OK] rust: Cargo.toml"
else
    say "  [SKIP] rust: Cargo.toml (unchanged)"
fi

# src/lib.rs
LIB_RS="${LANG_DIR}/src/lib.rs"
if should_regenerate "$LIB_RS" "$STRUCT_FILE"; then
    module_mods=""
    for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
        m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
        module_mods+="pub mod ${m_name};"$'\n'
    done

    vars_file=$(mktemp)
    {
        printf 'crate_name=%s\n' "$(encode_value "${CRATE_NAME}")"
        printf 'module_mods=%s\n' "$(encode_value "${module_mods}")"
    } > "$vars_file"
    if ! render_to_file "$LIB_RS" "rust" "lib" "$vars_file"; then
        cat > "$LIB_RS" <<EOF
//! ${CRATE_NAME} — 自动生成的库入口
//! Auto-generated by bootstrap.sh
${module_mods}
EOF
    fi
    rm -f "$vars_file"
    mark_generated "$LIB_RS" "$STRUCT_FILE"
    say "  [OK] rust: src/lib.rs"
else
    say "  [SKIP] rust: src/lib.rs (unchanged)"
fi

echo "  [OK] rust 生成完成: $LANG_DIR/"

# cargo check 验证
if command -v cargo >/dev/null 2>&1; then
    echo ""
    echo "  ▶ cargo check ..."
    if (cd "$LANG_DIR" && cargo check --quiet 2>&1); then
        echo "  [OK] cargo check 通过"
    else
        echo "  [FAIL] cargo check 失败（生成的代码无法编译）" >&2
        exit 1
    fi
    echo "  ▶ cargo test --no-run ..."
    if (cd "$LANG_DIR" && cargo test --no-run --quiet 2>&1); then
        echo "  [OK] cargo test --no-run 通过"
    else
        echo "  [WARN] cargo test --no-run 失败（不影响主流程，跳过）" >&2
    fi
else
    echo "  [WARN] cargo 未安装，跳过编译验证"
fi
