"""Component: {{component_name}} (module: {{module_name}})

{{description}}

Auto-generated by bootstrap.sh — implement __call__().
{{acceptance_criteria}}"""
from typing import Any, List
{{imports_block}}from ..base import Service as _BaseComponent


class {{component_name}}({{base_class}}):
    """{{description}}"""

    name: str = "{{component_name}}"
    exports: List[str] = {{exports_json}}
    imports: List[str] = {{imports_json}}
    optional: bool = {{optional_py}}
{{todos_block}}
    def __call__(self) -> Any:
        """执行 {{component_name}} 的核心逻辑"""
        raise NotImplementedError("{{component_name}}.__call__() 待实现")
