/**
 * Component: {{component_name}} (module: {{module_name}})
 *
 * {{description}}
 *
 * Auto-generated by bootstrap.sh — implement call().
{{exports_list}}{{todos_block}} {{acceptance_criteria}}*/
{{imports_block}}
/**
 * {{description}}
 */
export interface {{component_name}}Options {
  readonly name: string;
  readonly optional: boolean;
{{interface_fields}}
}

/**
 * {{description}}
 *
 * Auto-generated by bootstrap.sh.
 */
export class {{component_name}} implements {{component_name}}Options {
  public readonly name: string = "{{component_name}}";
  public readonly optional: boolean = {{optional_ts}};
{{class_fields}}

  /**
   * 执行 {{component_name}} 的核心逻辑
   * 待实现：在子类或本类中填充具体行为
   */
  public call(): unknown {
    throw new Error("{{component_name}}.call() 待实现");
  }
}

export default {{component_name}};
